items = {
0: {"name": "apple", "room": 8,"player":0,"stamina":5},
1: {"name": "banana","room": 4,"player":0,"stamina":5},
2: {"name": "orange","room": 99,"player":0,"stamina":5},
3: {"name": "apple","room": 87,"player":0,"stamina":5},
4: {"name": "banana","room": 63,"player":0,"stamina":5},
5: {"name": "orange","room": 65,"player":0,"stamina":5},
6: {"name": "apple","room": 72,"player":0,"stamina":5},
7: {"name": "banana","room": 45,"player":0,"stamina":5},
8: {"name": "orange","room": 29,"player":0,"stamina":5},
9: {"name": "apple","room": 18,"player":0,"stamina":5},
10: {"name": "banana","room": 7,"player":0,"stamina":5},
11: {"name": "orange","room": 12,"player":0,"stamina":5},
12: {"name": "apple","room": 91,"player":0,"stamina":5},
13: {"name": "banana","room": 33,"player":0,"stamina":5},
14: {"name": "orange","room": 60,"player":0,"stamina":5},
15: {"name": "apple","room": 44,"player":0,"stamina":5},
16: {"name": "banana","room": 69,"player":0,"stamina":5},
17: {"name": "orange","room": 52,"player":0,"stamina":5},
18: {"name": "apple","room": 3,"player":0,"stamina":5},
19: {"name": "banana","room": 16,"player":0,"stamina":5},
20: {"name": "orange","room": 49,"player":0,"stamina":5},
21: {"name": "banana","room": 82,"player":0,"stamina":5},
22: {"name": "orange","room": 90,"player":0,"stamina":5},
23: {"name": "apple","room": 1,"player":0,"stamina":5},
24: {"name": "banana","room": 5,"player":0,"stamina":5},
25: {"name": "orange","room": 93,"player":0,"stamina":5},
26: {"name": "apple","room": 71,"player":0,"stamina":5},
27: {"name": "banana","room": 29,"player":0,"stamina":5},
28: {"name": "orange","room": 23,"player":0,"stamina":5},
29: {"name": "apple","room": 33,"player":0,"stamina":5}
}