rooms = {"Vine of Mire": "The room has a huge vine running up through the ceiling.",
"Bright Flat": "There is a bright loght comming through the ceiling and shining onto a small pool in the middle of the room.",
"Ash County": "This room is so large it seem like a country.",
"Southknoll	": "There is a knoll of grass that seems to have grown around the most southern point in the room.",
"Goldwood": "A grove of trees with bark a bright shiny yellow.",
"Inns lake": "This underground lake is vast, but there is boat on the water. you cant see across it.",
"Archers rock": "THere is a rock in here with a a large whole cut into it. You see a few old arrow heads in inside it.",
"Owlgreen": "You stumble into a very green area with hundreds of hooting owls. It is pretty creepy.",
"Valleylock": "You walk into the room and it is as wide as a glacier cravas and as at leas a mile long. ",
"Helmsrapid": "You walk it and there is a small bridge running accross an underground rapid.",
"Crystalmoors": "The vast purpl crystals are mesmerizing you could stare at them for hours.",
"True Strait": "You see the narrow path.",
"Redcrypt": "You wish you were not colorblind.",
"Westronwash": "If your car was in this room you would wash it.",
"Westronhold": "Hold on! Hold on!",
"Witch Run": "Why are these old ladies signing up for a 5k?",
"Sorcerers Wilds": "Look out for gandalf, he is a wildman.",
"Stonedowns": "There is no place like home, or stonedowns.",
"Elmpeak": "There is now way to open the trapdoor.",
"Arrach Bridge": "Don't fall off the bridge",
"Blessed Gorge": "You have stepped into a sacred place.",
"Mossy road": "The floor is slippery in here, is that moss?",
"Archerskeep": "You could really use a bow and arrows.",
"Sparrow hollow": "There is something flying around in here.",
"Shieldgate": "You don't know why but this room has stalagtites.",
"Rogue passage": "There are people watching star wars in here.",
"Stoutmoor": "You wish that you could eat a lot of food right now.",
"Leechkeep": "The sound of hissing comes from the back of the room.",
"Cragpeak": "The floor in this room is really bumpy.",
"Mosspoint": "There is a big x on the floor covered in moss.",
"Scout Hill": "You found a woodcarving merit badge!!",
"Grey Divide": "Everything is in grayscale and divided.",
"Marble Plateau": "This plateau is made of marbles and feels strange under your feet.",
"Low Ruin": "This ruin is below sea level, so luckily it isn't raining.",
"Lookout Road": "You look out from your spot on the road and the wind hits you in the face.",
"Carn River": "You see a slow flowing river with stones piled up on the banks.",
"Bronzewood Bluff": "You are not bluffing, the trees in here are shiny and brown like bronze.",
"Dungeon Basin": "There is a basin full of glowing purple liquid that you probably should not touch.",
"Mud Dome": "The dome is dark and cool inside, a perfect place to rest.",
"Mink Canyon": "What is that you just heard, it sounds like water.",
"Mud Divide": "It is just sandy right now.",
"Long Divide": "This room is sooooo long.",
"Piratescleft": "There is a statue of a pirate, you don't think it will help you on your quest.",
"Keelpond": "There are no fish in the pond.",
"Tunnels of the Phantom Guardian": "You have entered the crypt of the phantom guardian.",
"Haunt of the Destroyed Monk": "The monk in here is nothing special, he's not even bald!",
"Burrows of the Spirit Priest": "The priest of spirit is very into yoga!",
"The Dragon Grotto": "Why does the dragon have to live in a grotto?",
"The Fire Burrow": "You see your childhood flash before your eyes.",
"The Lion Tooth Quarter": "Are there animal dentists? You don't think so.",
"The Raging Pit": "There is a feeling of general rage in this room.",
"The Courage Cell": "You feel so courageous!",
"Labyrinth of the Phantom King": "It is said the king was very kind.",
"Vault of the Furious Dragon": "The dragon gets really mad is you step on his tail.",
"Grotto of the Dishonored Arachnid": "That spider is so shamefull.",
"Vault of the Thunder Forest": "Why is it so loud in this room?",
"The Violent Haunt": "The ghosts in here have been very docile so far.",
"The Flowing Delve": "You have found the flowing delve!",
"The Prisoner Quarter": "There are old chains in this room, it looks like some one used to keep captives in here.",
"The Volcanic Delve": "Don't step in the lava!The room has old hyrogliph paintings a large valcano errupting.",
"The Crescent Moon Vault": "The light of the moon filters through the roof.",
"The Sanguine Cells": "There are forlorn squirrells in here.",
"The Eternal Rest Point": "Wow you are feeling sleepy. Don't die here!",
"The Eternal Labyrinth": "This is a maze inside a maze.People have gotten lost in the labrynth of this room and never made it, be weery of which way you enter.",
"The Forsaken Cells": "There is nobody in here...nice more cheese-its for you!his room is teaming with bacteria and viruses.",
"The Murky Cells": "Super murky and kind of gross inside",
"The Wailing Tunnels": "Is that moaning mertle?he wind blows through to tunnels and causes a horrendous wailing noise. Or it's ghosts.",
"The Ogre Caverns": "Strange, the ogre has two eyes.here are huge piles of ogre bones towards the edges of the room.",
"la Tanière Terrible": "Something is terrible in here. You should probably get out!",
"la Grotte Cachée": "Wow it is dark in here.",
"les Cavernes Invisibles": "There seems to be something invisible in here, but you don't know because it's invisible",
"les Tunnels de Bronze": "Oh no a monster, oh actually it's just a rock.",
"les Tunnels Brûlés": "You're getting hungry, hopefully there is some food in here.",
"le Tunnel Sec": "Is it snowing in here?",
"le Donjon Secret": "This room has 3 walls. Nice!",
"The Lower Quarters": "This is your favorite room yet!",
"Cavern of the Fallen Widow": "What was that noise?",
"The Cold Maze": "You wish you had thought to bring you ipod.",
"The Collapsing Tomb": "You find a friendly gnome in this room.",
"The Overhanging Catacomb": "This room has a gravel floor.",
"The Fractured Chamber": "This is the fracture chamber room.",
"The Fire Tunnel": "There is no fire in here but you still want to move fast.",
"Cavern of the Hidden Eagle": "You don't see a hidden eagle but eagles are good at hiding, especialy hidden eagles.",
"Delve of the Conquered Soldier": "You will never be conquered!",
"The Chaotic Cavern": "The cave room seems chaotic.",
"The Infernal Lair": "There is a rug on the floor, you can't move it though.",
"The Phoenix Pit": "Is that dumbledore?",
"The Unknown Vault": "The contents of the room are unknown, you'll have to look around.",
"les Terriers en Cristal": "You hear french music.",
"la Grotte Dansante": "There is some writing on the wall but you don't know french.",
"la Caverne Démoniaque": "This cavern is more like a maze, don't get lost.",
"les Donjons Détruits": "THe room is dark but you find places on the walls were there are lanturns and long wooden table in the middle.",
"le Terrier d'Arrogance": "There is an inscription on the side of the wall, that says beware the arrogant, for they will only find hardship.",
"la Tanière Lugubre": "The room is is filled with onld stained paintings, you can see one of them looks like the painting of lake high in the mountains.",
"le Tunnel Ancien": "This tunnel must be close to the surface because it you can see light coming in through cracks in the ceiling.",
"le Tunnel d'Hurlement": "This tunnels is windy and has a fewi doors on the sides. some look caved in.",
"le Repaire du Feu": "This is a vary narrow path, be careful you don't get stuck.",
"The Lucent Burrow": "Be careful in this room, people tend to lose a bit of themselves in here.",
"The Mirage Vault": "This vault is filled with crystals. So that are so large and smoothe you can see your reflection in them.",
"The Wondering Chambers": "THis vast chamber is so high and wide that your not sure which direction you should go. If you continue on will you be able to find your way back?",
}