# Generated by Django 3.0.2 on 2020-01-09 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adventure', '0004_auto_20200109_0419'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='items',
            field=models.CharField(default='AAAGH', max_length=100),
        ),
    ]
