# Generated by Django 3.0.2 on 2020-01-09 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adventure', '0005_room_items'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='items',
        ),
    ]
