# Generated by Django 3.0.2 on 2020-01-09 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adventure', '0006_remove_room_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='z',
            field=models.IntegerField(default=0),
        ),
    ]
