# Generated by Django 3.0.2 on 2020-01-09 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adventure', '0008_remove_room_z'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='stamina',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='player',
            name='x',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='y',
            field=models.IntegerField(default=0),
        ),
    ]
